/*
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
/* eslint-disable max-len, object-property-newline */
import { defineMessages } from 'react-intl';

const strings = defineMessages({
  // Common
  KYLIN_MDX: { defaultMessage: 'Kylin MDX', id: 'KYLIN_MDX' },
  NOTIFICATION: { defaultMessage: 'Notification', id: 'NOTIFICATION' },
  OK: { defaultMessage: 'OK', id: 'OK' },
  DETAIL: { defaultMessage: 'Detail', id: 'DETAIL' },
  DATASET: { defaultMessage: 'Dataset', id: 'DATASET' },
  QUERY_HISTORY: { defaultMessage: 'Query History', id: 'QUERY_HISTORY' },
  DATASET_ROLE: { defaultMessage: 'Dataset Role', id: 'DATASET_ROLE' },
  SIGNIN: { defaultMessage: 'Sign In', id: 'SIGNIN' },
  NEXT: { defaultMessage: 'Next', id: 'NEXT' },
  EXIT: { defaultMessage: 'Exit', id: 'EXIT' },
  PREVIOUS: { defaultMessage: 'Previous', id: 'PREVIOUS' },
  NAME: { defaultMessage: 'Name', id: 'NAME' },
  NO_DATA: { defaultMessage: 'No Data', id: 'NO_DATA' },
  NONE: { defaultMessage: 'None', id: 'NONE' },
  NORMAL: { defaultMessage: 'NORMAL', id: 'NORMAL' },
  ERROR: { defaultMessage: 'Error', id: 'ERROR' },
  BROKEN: { defaultMessage: 'ERROR', id: 'BROKEN' },
  EDIT: { defaultMessage: 'Edit', id: 'EDIT' },
  VIEW: { defaultMessage: 'View', id: 'VIEW' },
  DELETE: { defaultMessage: 'Delete', id: 'DELETE' },
  CONFIRM_DELETE: { defaultMessage: 'Confirm Delete', id: 'CONFIRM_DELETE' },
  BACK_TO_EDIT: { defaultMessage: 'Back to Edit', id: 'BACK_TO_EDIT' },
  RENAME: { defaultMessage: 'Rename', id: 'RENAME' },
  CLONE: { defaultMessage: 'Clone', id: 'CLONE' },
  EXPORT: { defaultMessage: 'Export', id: 'EXPORT' },
  ACCESS_CONTROL: { defaultMessage: 'Access Control', id: 'ACCESS_CONTROL' },
  RETURN: { defaultMessage: 'Return', id: 'RETURN' },
  MORE: { defaultMessage: 'More', id: 'MORE' },
  ACTIONS: { defaultMessage: 'Actions', id: 'ACTIONS' },
  ACTION: { defaultMessage: 'Action', id: 'ACTION' },
  TYPE: { defaultMessage: 'Type', id: 'TYPE' },
  MODIFY_TIME: { defaultMessage: 'Last Modified Time', id: 'MODIFY_TIME' },
  LAST_MODIFIED_C: { defaultMessage: 'Last Modified:', id: 'LAST_MODIFIED_C' },
  DESCRIPTION: { defaultMessage: 'Description', id: 'DESCRIPTION' },
  STATUS: { defaultMessage: 'Status', id: 'STATUS' },
  USER: { defaultMessage: 'User', id: 'USER' },
  USER_GROUP: { defaultMessage: 'Group', id: 'USER_GROUP' },
  ROLE: { defaultMessage: 'Role', id: 'ROLE' },
  SAVE: { defaultMessage: 'Save', id: 'SAVE' },
  YES: { defaultMessage: 'Yes', id: 'YES' },
  NO: { defaultMessage: 'No', id: 'NO' },
  TO: { defaultMessage: 'to', id: 'TO' },
  FILTER: { defaultMessage: 'Filter', id: 'FILTER' },
  SEARCH: { defaultMessage: 'Search', id: 'SEARCH' },
  CANCEL: { defaultMessage: 'Cancel', id: 'CANCEL' },
  SUBMIT: { defaultMessage: 'Submit', id: 'SUBMIT' },
  DOWNLOAD: { defaultMessage: 'Download', id: 'DOWNLOAD' },
  DOWNLOADING: { defaultMessage: 'Downloading {progress}%...', id: 'DOWNLOADING' },
  VALIDATING: { defaultMessage: 'Validating...', id: 'VALIDATING' },
  PLEASE_ENTER: { defaultMessage: 'Please enter.', id: 'PLEASE_ENTER' },
  PLEASE_SELECT_ENTITY: { defaultMessage: 'Please select a {entity}.', id: 'PLEASE_SELECT_ENTITY' },
  PLEASE_ENTER_NAME: { defaultMessage: 'Please enter name.', id: 'PLEASE_ENTER_NAME' },
  FIELD_IS_EMPTY: { defaultMessage: 'This field cannot be empty.', id: 'FIELD_IS_EMPTY' },
  FILE_IS_EMPTY: { defaultMessage: 'File cannot be empty.', id: 'FILE_IS_EMPTY' },
  DESCRIPTION_TOO_LONG: { defaultMessage: 'The description length cannot be greater than {maxLength}.', id: 'DESCRIPTION_TOO_LONG' },
  VALID_NAME_WITH_CHINESE: { defaultMessage: 'Only chinese, letters, numbers and _ are valid.', id: 'VALID_NAME_WITH_CHINESE' },
  INVALID_NAME: { defaultMessage: 'Invalid name. Only letters, numbers and _ are supported in a valid name.', id: 'INVALID_NAME' },
  INVALID_NAME_WITH_CHINESE: { defaultMessage: 'Invalid name. Only Chinese, letters, numbers and _ are supported in a valid name.', id: 'INVALID_NAME_WITH_CHINESE' },
  INVALID_NAME_WITH_CHINESE_AND_SPACE: { defaultMessage: 'Invalid name. Only Chinese, letters, numbers, space and _ are supported in a valid name.', id: 'INVALID_NAME_WITH_CHINESE_AND_SPACE' },
  NO_PROJECT: { defaultMessage: 'No access to the project. Please contact your Kylin administrator for permission.', id: 'NO_PROJECT' },
  RESART_SYNC_TASK_TIP_FOR_SYSTEM_ADMIN: { defaultMessage: 'The task of synchronizing Kylin data has been stopped. \r\nPlease go to the administrator page to restart the service.\r\nIf you have changed the username or password for connecting, please enter the administrator page to modify the username and password to restart the service.', id: 'RESART_SYNC_TASK_TIP_FOR_SYSTEM_ADMIN' },
  RESART_SYNC_TASK_TIP_FOR_PROJECT_ADMIN: { defaultMessage: 'The task of synchronizing Kylin data has stopped. \r\nPlease contact your system administrator to restart the synchronization task.', id: 'RESART_SYNC_TASK_TIP_FOR_PROJECT_ADMIN' },
  SECONDS: { defaultMessage: 'S', id: 'SECONDS' },
  CONFIRM: { defaultMessage: 'Confirm', id: 'CONFIRM' },
  SUCCESS: { defaultMessage: 'Success', id: 'SUCCESS' },
  FAILURE: { defaultMessage: 'Failure', id: 'FAILURE' },
  SEMICOLON: { defaultMessage: ':', id: 'SEMICOLON' },
  TRUE: { defaultMessage: 'True', id: 'TRUE' },
  FALSE: { defaultMessage: 'False', id: 'FALSE' },
  SEARCH_BY: { defaultMessage: 'Search by ', id: 'SEARCH_BY' },
  COPY: { defaultMessage: 'Copy', id: 'COPY' },
  SCALE_YEAR: { defaultMessage: 'year(s)', id: 'SCALE_YEAR' },
  SCALE_MONTH: { defaultMessage: 'month(s)', id: 'SCALE_MONTH' },
  SCALE_DAY: { defaultMessage: 'day(s)', id: 'SCALE_DAY' },
  SCALE_HOUR: { defaultMessage: 'hour', id: 'SCALE_HOUR' },
  SCALE_MINUTE: { defaultMessage: 'min', id: 'SCALE_MINUTE' },
  SCALE_SECOND: { defaultMessage: 's', id: 'SCALE_SECOND' },
  SCALE_MILLS: { defaultMessage: 'ms', id: 'SCALE_MILLS' },
  EXPAND_VIEW_MORE_INFO: { defaultMessage: 'Expand the table row to see more information.', id: 'EXPAND_VIEW_MORE_INFO' },
  SHOW_MORE: { defaultMessage: 'Show more', id: 'SHOW_MORE' },
  SHOW_LESS: { defaultMessage: 'Show less', id: 'SHOW_LESS' },
  LAST_24_HOURS: { defaultMessage: 'Last 24 hours', id: 'LAST_24_HOURS' },
  LAST_7_DAYS: { defaultMessage: 'Last 7 days', id: 'LAST_7_DAYS' },
  LAST_30_DAYS: { defaultMessage: 'Last 30 days', id: 'LAST_30_DAYS' },
  BETWEEN_AND: { defaultMessage: '{restItems} and {lastItem}', id: 'BETWEEN_AND' },
  BETWEEN_OR: { defaultMessage: '{restItems} or {lastItem}', id: 'BETWEEN_OR' },
  BETWEEN_SPLIT: { defaultMessage: ', ', id: 'BETWEEN_SPLIT' },
  OTHER: { defaultMessage: 'Other', id: 'OTHER' },
  PLEASE_SEARCH_AND_SELECT_ONE: { defaultMessage: 'Please search and select one', id: 'PLEASE_SEARCH_AND_SELECT_ONE' },
  PLEASE_SELECT: { defaultMessage: 'Please select', id: 'PLEASE_SELECT' },
  SUPPORT_FILE: { defaultMessage: 'Only support {type} file. Please select again.', id: 'SUPPORT_FILE' },
  // PageHeader
  ENTER_MANAGEMENT: { defaultMessage: 'Enter Management', id: 'ENTER_MANAGEMENT' },
  EXIT_MANAGEMENT: { defaultMessage: 'Exit Management', id: 'EXIT_MANAGEMENT' },
  KYLIN_INSIGHT_MANUAL: { defaultMessage: 'Kylin MDX Manual', id: 'KYLIN_INSIGHT_MANUAL' },
  ABOUT_KYLIN_INSIGHT: { defaultMessage: 'About Kylin MDX', id: 'ABOUT_KYLIN_INSIGHT' },
  HELP: { defaultMessage: 'Help', id: 'HELP' },
  LOGOUT: { defaultMessage: 'Logout', id: 'LOGOUT' },
  // PageFooter
  COPYRIGHT_1: { defaultMessage: '© {year}', id: 'COPYRIGHT_1' },
  COPYRIGHT_2: { defaultMessage: 'Kyligence, Inc.', id: 'COPYRIGHT_2' },
  COPYRIGHT_3: { defaultMessage: 'All rights reserved.', id: 'COPYRIGHT_3' },
  // PageMenu
  NOTICE: { defaultMessage: 'Notice', id: 'NOTICE' },
  SWITCH_LOST_EDIT: { defaultMessage: 'You will lose unsaved content if you change to another page.', id: 'SWITCH_LOST_EDIT' },
  // Login
  USERNAME: { defaultMessage: 'Username', id: 'USERNAME' },
  PASSWORD: { defaultMessage: 'Password', id: 'PASSWORD' },
  FORGET_PASSWORD: { defaultMessage: 'Forget Password', id: 'FORGET_PASSWORD' },
  WELCOME_MDX: { defaultMessage: 'Welcome to Kylin MDX', id: 'WELCOME_MDX' },
  MDX_DESCRIPTION: { defaultMessage: 'A Unified Business Semantic Layer', id: 'MDX_DESCRIPTION' },
  INTRODUCTION: { defaultMessage: 'Introduction', id: 'INTRODUCTION' },
  MANUAL: { defaultMessage: 'Manual', id: 'MANUAL' },
  CONTACT_US: { defaultMessage: 'Contact Us', id: 'CONTACT_US' },
  USERNAME_TOO_LONG: { defaultMessage: 'The username length cannot be greater than {maxLength}.', id: 'USERNAME_TOO_LONG' },
  // Overview
  OVERVIEW: { defaultMessage: 'Overview', id: 'OVERVIEW' },
  QUERY_STATISTICS: { defaultMessage: 'Query Statistics', id: 'QUERY_STATISTICS' },
  VIEW_QUERY_HISTORY: { defaultMessage: 'View query history', id: 'VIEW_QUERY_HISTORY' },
  ACTIVE_USERS: { defaultMessage: 'Active Users', id: 'ACTIVE_USERS' },
  MDX_QUERIES: { defaultMessage: 'MDX Queries', id: 'MDX_QUERIES' },
  MDX_FAILED_QUERIES: { defaultMessage: 'MDX Failed Queries', id: 'MDX_FAILED_QUERIES' },
  AVG_QUERIES_PER_USER: { defaultMessage: 'AVG. Queries per User', id: 'AVG_QUERIES_PER_USER' },
  AVG_QUERY_TIME: { defaultMessage: 'AVG. Query Time', id: 'AVG_QUERY_TIME' },
  TOTAL_AVG_QUERY_TIME: { defaultMessage: 'Total AVG. Query Time', id: 'TOTAL_AVG_QUERY_TIME' },
  QUERY_TREND: { defaultMessage: 'Query Trend', id: 'QUERY_TREND' },
  QUERIES_COUNT: { defaultMessage: 'Queries', id: 'QUERIES_COUNT' },
  TOTAL_QUERIES: { defaultMessage: 'Total Queries', id: 'TOTAL_QUERIES' },
  FAILED_QUERIES: { defaultMessage: 'Failed Queries', id: 'FAILED_QUERIES' },
  TOTAL_FAILED_QUERIES: { defaultMessage: 'Total Failed Queries', id: 'TOTAL_FAILED_QUERIES' },
  QUERY_TIME: { defaultMessage: 'Query Time', id: 'QUERY_TIME' },
  RANKING: { defaultMessage: 'Ranking', id: 'RANKING' },
  POPULAR_DATASETS: { defaultMessage: 'Popular Datasets', id: 'POPULAR_DATASETS' },
  MOST_USED_DATASETS: { defaultMessage: '10 Most Used Datasets', id: 'MOST_USED_DATASETS' },
  LEAST_USED_DATASETS: { defaultMessage: '10 Least Used Datasets', id: 'LEAST_USED_DATASETS' },
  RANK_BY_TIMES_OF_USE: { defaultMessage: 'Rank by Times of Use', id: 'RANK_BY_TIMES_OF_USE' },
  EMPTY_DATASETS: { defaultMessage: 'No statistics, please add the dataset first.', id: 'EMPTY_DATASETS' },
  // Dataset List
  CREATE_USER: { defaultMessage: 'Create User', id: 'CREATE_USER' },
  SEARCH_DATASET: { defaultMessage: 'Search Dataset', id: 'SEARCH_DATASET' },
  CONFIRM_DELETE_DATASET: { defaultMessage: 'Are you sure to delete dataset [{datasetName}]?', id: 'CONFIRM_DELETE_DATASET' },
  CONFIRM_DELETE_DATASETS: { defaultMessage: 'Are you sure to delete selected datasets?', id: 'CONFIRM_DELETE_DATASETS' },
  DELETE_DATASET_SUCCESS: { defaultMessage: 'Delete dataset successfully.', id: 'DELETE_DATASET_SUCCESS' },
  DATASET_NAME_IMPORT_DUPLICATE: { defaultMessage: 'The dataset [{datasetName}] already exists and cannot be imported.', id: 'DATASET_NAME_IMPORT_DUPLICATE' },
  DATASET_PROJECT_IMPORT_INVALID: { defaultMessage: 'The project in the dataset is [{project}], which is inconsistent with the current project and cannot be imported.', id: 'DATASET_PROJECT_IMPORT_INVALID' },
  SUCCESS_IMPORT_DATASET: { defaultMessage: 'The dataset was successfully imported.', id: 'SUCCESS_IMPORT_DATASET' },
  SUCCESS_EXPORT_DATASET: { defaultMessage: 'The request was successful. The metadata of the dataset is about to be exported.', id: 'SUCCESS_EXPORT_DATASET' },
  FAILED_UPLOAD_WITH_ERROR_JSON_PARSE: { defaultMessage: 'Parsing the file failed. Please check that the dataset file is complete.', id: 'FAILED_UPLOAD_WITH_ERROR_JSON_PARSE' },
  FAILED_UPLOAD_WITH_ERROR_FILE_TYPE: { defaultMessage: 'File type error. Import metadata only accept {type} file, please choose to upload the file again.', id: 'FAILED_UPLOAD_WITH_ERROR_FILE_TYPE' },
  CREATE_DATASET: { defaultMessage: 'Create Dataset', id: 'CREATE_DATASET' },
  IMPORT_DATASET: { defaultMessage: 'Import Dataset', id: 'IMPORT_DATASET' },
  EXPORT_DATASET: { defaultMessage: 'Export Dataset', id: 'EXPORT_DATASET' },
  // Query History
  START_TIME: { defaultMessage: 'Start Time', id: 'START_TIME' },
  EXECUTE_TIME: { defaultMessage: 'Execution Time', id: 'EXECUTE_TIME' },
  LESS_THAN_ONE_SECOND: { defaultMessage: '< 1s', id: 'LESS_THAN_ONE_SECOND' },
  BIGGER_THAN_N_UNIT: { defaultMessage: '> {n}{unit}', id: 'BIGGER_THAN_N_UNIT' },
  SEARCH_QUERY_ID_OR_USERNAME: { defaultMessage: 'Search by user or query ID', id: 'SEARCH_QUERY_ID_OR_USERNAME' },
  QUERY_CONTENT: { defaultMessage: 'Query', id: 'QUERY_CONTENT' },
  APPLICATION: { defaultMessage: 'Application', id: 'APPLICATION' },
  QUERY_STATUS: { defaultMessage: 'Status', id: 'QUERY_STATUS' },
  QUERY_NODE: { defaultMessage: 'Query Node', id: 'QUERY_NODE' },
  SHOW_FAILED_SQL_QUERY_ONLY: { defaultMessage: 'Show Failed SQL Query Only', id: 'SHOW_FAILED_SQL_QUERY_ONLY' },
  MDX_QUERY: { defaultMessage: 'MDX Query', id: 'MDX_QUERY' },
  SQL_QUERY: { defaultMessage: 'SQL Query', id: 'SQL_QUERY' },
  QUERY_ID: { defaultMessage: 'Query ID', id: 'QUERY_ID' },
  MDX_QUERY_STATUS: { defaultMessage: 'MDX Query Status', id: 'MDX_QUERY_STATUS' },
  USE_MDX_CACHE: { defaultMessage: 'Use MDX Cache', id: 'USE_MDX_CACHE' },
  USE_OTHER_ENGINE: { defaultMessage: 'Use Other Engine', id: 'USE_OTHER_ENGINE' },
  TIMEOUT: { defaultMessage: 'Timeout', id: 'TIMEOUT' },
  MULTI_DIM_DATASET_TIME: { defaultMessage: 'Time for Creating Multidimensional Dataset', id: 'MULTI_DIM_DATASET_TIME' },
  TIME_FOR_MARSHALL_SOAP_MESSAGE: { defaultMessage: 'Time for Marshall Soap Message', id: 'TIME_FOR_MARSHALL_SOAP_MESSAGE' },
  USE_GATEWAY: { defaultMessage: 'Use Gateway', id: 'USE_GATEWAY' },
  NETWORK_PACKAGE: { defaultMessage: 'Network Package', id: 'NETWORK_PACKAGE' },
  SQL_QUERY_STATUS: { defaultMessage: 'SQL Query Status', id: 'SQL_QUERY_STATUS' },
  USE_SQL_CACHE: { defaultMessage: 'Use SQL Cache', id: 'USE_SQL_CACHE' },
  SQL_EXECUTION_TIME: { defaultMessage: 'SQL Execution Time', id: 'SQL_EXECUTION_TIME' },
  SYSTEM_ID: { defaultMessage: 'System ID', id: 'SYSTEM_ID' },
  KYLIN_QUERY_ID: { defaultMessage: 'Kylin Query ID', id: 'KYLIN_QUERY_ID' },
  // Dataset Role List
  MODIFY_EXPRESSION: { defaultMessage: 'Modify Expression', id: 'MODIFY_EXPRESSION' },
  ERROR_DATASET_CHECK_MSG: { defaultMessage: 'The following items are incorrect. Please modify and resubmit later.', id: 'ERROR_DATASET_CHECK_MSG' },
  DATASET_ROLE_C: { defaultMessage: 'Dataset Role:', id: 'DATASET_ROLE_C' },
  FILTER_USERS: { defaultMessage: 'Filter Users', id: 'FILTER_USERS' },
  DEFAULT_ROLE: { defaultMessage: 'Default Roles', id: 'DEFAULT_ROLE' },
  CUSTOM_ROLE: { defaultMessage: 'Created Roles', id: 'CUSTOM_ROLE' },
  ASSIGNED_USERS: { defaultMessage: 'Assigned User(s)', id: 'ASSIGNED_USERS' },
  UNASSIGNED_USERS: { defaultMessage: 'Unassigned User(s)', id: 'UNASSIGNED_USERS' },
  DATASET_ROLE_NAME_TOO_LONG: { defaultMessage: 'Dataset role name length cannot be greater than {maxLength}.', id: 'DATASET_ROLE_NAME_TOO_LONG' },
  PLEASE_ENTER_ROLE_NAME: { defaultMessage: 'Please enter the role name.', id: 'PLEASE_ENTER_ROLE_NAME' },
  EXIT_LOST_EDIT: { defaultMessage: 'You will lose unsaved content if you exit the page.', id: 'EXIT_LOST_EDIT' },
  SWITCH_LOST_EDIT_ROLE: { defaultMessage: 'You will lose unsaved content if you change to another role.', id: 'SWITCH_LOST_EDIT_ROLE' },
  CONFIRM_DELETE_DATASET_ROLE: { defaultMessage: 'Are you sure to delete dataset role [{roleName}]?', id: 'CONFIRM_DELETE_DATASET_ROLE' },
  CREATE_DATASET_ROLE_SUCCESS: { defaultMessage: 'Dataset role [{roleName}] is created successfully.', id: 'CREATE_DATASET_ROLE_SUCCESS' },
  MODIFY_DATASET_ROLE_SUCCESS: { defaultMessage: 'Dataset role [{roleName}] is modified successfully.', id: 'MODIFY_DATASET_ROLE_SUCCESS' },
  DELETE_DATASET_ROLE_SUCCESS: { defaultMessage: 'Dataset role [{roleName}] is deleted successfully.', id: 'DELETE_DATASET_ROLE_SUCCESS' },
  DATASET_ADMIN_DESC: { defaultMessage: 'This role is an admin role with all semantic information access to all datasets.', id: 'DATASET_ADMIN_DESC' },
  // Diagnosis
  DIAGNOSIS: { defaultMessage: 'Diagnosis', id: 'DIAGNOSIS' },
  EXPORT_DIAGNOSIS_PACKAGE: { defaultMessage: 'Export Diagnosis Package', id: 'EXPORT_DIAGNOSIS_PACKAGE' },
  SELECT_DATE_RANGE: { defaultMessage: 'Please select date range', id: 'SELECT_DATE_RANGE' },
  EMPTY_CLUSTERS: { defaultMessage: 'You have not configured any node information. Please check the configuration information of insight.mdx.cluster.nodes in the configuration file.', id: 'EMPTY_CLUSTERS' },
  DATE_RANGE: { defaultMessage: 'Date range', id: 'DATE_RANGE' },
  SERVER: { defaultMessage: 'Server', id: 'SERVER' },
  TODAY: { defaultMessage: 'Today', id: 'TODAY' },
  LAST_3_DAYS: { defaultMessage: 'Last 3 days', id: 'LAST_3_DAYS' },
  LAST_1_MONTH: { defaultMessage: 'Last month', id: 'LAST_1_MONTH' },
  CUSTOMIZE: { defaultMessage: 'Customize', id: 'CUSTOMIZE' },
  PLEASE_SELECT_DATE_RANGE: { defaultMessage: 'Please select the date range.', id: 'PLEASE_SELECT_DATE_RANGE' },
  PLEASE_SELECT_SERVER: { defaultMessage: 'Please select at least one server.', id: 'PLEASE_SELECT_SERVER' },
  GENERATE_A_PACKAGE: { defaultMessage: 'Generate a package', id: 'GENERATE_A_PACKAGE' },
  DIAGNOSIS_DOWNLOAD_NOTICE: { defaultMessage: 'After the diagnostic package is generated, please click {icon} to manually download to the local.', id: 'DIAGNOSIS_DOWNLOAD_NOTICE' },
  RETRY: { defaultMessage: 'Retry', id: 'RETRY' },
  SHOW_DETAILS: { defaultMessage: 'Show details', id: 'SHOW_DETAILS' },
  HIDE_DETAILS: { defaultMessage: 'Hide details', id: 'HIDE_DETAILS' },
  EXTRACT_PACKAGE_INFO: { defaultMessage: 'Extracting packaging information.', id: 'EXTRACT_PACKAGE_INFO' },
  START_COMPRESSION: { defaultMessage: 'Start compression.', id: 'START_COMPRESSION' },
  PACKAGE_COMPLETE: { defaultMessage: 'Packaging is complete.', id: 'PACKAGE_COMPLETE' },
  PACKAGE_ERROR: { defaultMessage: 'An exception occurred while generating the diagnostic package.', id: 'PACKAGE_ERROR' },
  PACKAGE_WAITTING: { defaultMessage: 'The package is downloading, you can click to download again after {timer} seconds.', id: 'PACKAGE_WAITTING' },
  // Configuration
  CONFIGURATION: { defaultMessage: 'Configuration', id: 'CONFIGURATION' },
  KYLIN_NODE_CONFIGURATION: { defaultMessage: 'Kylin node configuration', id: 'KYLIN_NODE_CONFIGURATION' },
  KYLIN_IP_C: { defaultMessage: 'Kylin IP:', id: 'KYLIN_IP_C' },
  KYLIN_PORT_C: { defaultMessage: 'Kylin Port:', id: 'KYLIN_PORT_C' },
  SYNC_TASK_STATUS_C: { defaultMessage: 'Sync Task Status:', id: 'SYNC_TASK_STATUS_C' },
  LAST_SYNC_TIME_C: { defaultMessage: 'Last sync time:', id: 'LAST_SYNC_TIME_C' },
  CONNECTION_USER_C: { defaultMessage: 'Connection user:', id: 'CONNECTION_USER_C' },
  ACTIVE: { defaultMessage: 'Running', id: 'ACTIVE' },
  STARTING: { defaultMessage: 'Starting', id: 'STARTING' },
  INACTIVE: { defaultMessage: 'Stopped', id: 'INACTIVE' },
  RESTART_SYNC_TASK: { defaultMessage: 'Restart sync task', id: 'RESTART_SYNC_TASK' },
  EDIT_USER_INFORMATION: { defaultMessage: 'Edit user information', id: 'EDIT_USER_INFORMATION' },
  SUCCESS_EDIT_CONNECTION_USER: { defaultMessage: 'User information modified successfully. The system will restart the synchronization task. And sync the license information.', id: 'SUCCESS_EDIT_CONNECTION_USER' },
  SUCCESS_RESTART_SYNC_TASK: { defaultMessage: 'The verification was successful. The system will restart the synchronization task. And sync the license information.', id: 'SUCCESS_RESTART_SYNC_TASK' },
  // Toolkit
  TOOLKIT: { defaultMessage: 'Toolkit', id: 'TOOLKIT' },
  EXCEL_REPAIR_TOOL: { defaultMessage: 'Excel Repair Tool', id: 'EXCEL_REPAIR_TOOL' },
  EXCEL_REPAIR_TOOL_DESC_1: { defaultMessage: 'Usage Guidelines:', id: 'EXCEL_REPAIR_TOOL_DESC_1' },
  EXCEL_REPAIR_TOOL_DESC_2: { defaultMessage: '1. This tool is suitable for the original Excel file which has refresh exception caused by model changes (there is redundant information in Schema)', id: 'EXCEL_REPAIR_TOOL_DESC_2' },
  EXCEL_REPAIR_TOOL_DESC_3: { defaultMessage: '2. Please make sure that the data source connected in the Excel file only contains Kylin\'s data source', id: 'EXCEL_REPAIR_TOOL_DESC_3' },
  EXCEL_REPAIR_TOOL_DESC_4: { defaultMessage: '3. Temporarily only support the repair of one Excel file at a time, and the size is not more than {fileLimit}', id: 'EXCEL_REPAIR_TOOL_DESC_4' },
  EXCEL_REPAIR_TOOL_DESC_5: { defaultMessage: '4. Please click "Select..." to select the file to be repaired, and then click "Repair & Download" to obtain the repaired new file', id: 'EXCEL_REPAIR_TOOL_DESC_5' },
  EXCEL_REPAIR_TOOL_DESC_6: { defaultMessage: '5. It is recommended to use Chrome browser', id: 'EXCEL_REPAIR_TOOL_DESC_6' },
  CLICK_UPLOAD_EXCEL: { defaultMessage: 'Click here to upload excel file, file limit {fileLimit}.', id: 'CLICK_UPLOAD_EXCEL' },
  DONT_REFRESH_PAGE: { defaultMessage: 'Don\'t refresh page.', id: 'DONT_REFRESH_PAGE' },
  UPLOAD_FILE_STATUS: { defaultMessage: 'The file is uploading {progress}%.', id: 'UPLOAD_FILE_STATUS' },
  DOWNLOAD_FILE_STATUS: { defaultMessage: 'The file is downloading {progress}%.', id: 'DOWNLOAD_FILE_STATUS' },
  SELECT: { defaultMessage: 'Select...', id: 'SELECT' },
  SCANNING_FILE: { defaultMessage: 'Scanning file...', id: 'SCANNING_FILE' },
  REPAIR_DOWNLOAD: { defaultMessage: 'Repair & Download', id: 'REPAIR_DOWNLOAD' },
  NON_KYLIN_SOURCE: { defaultMessage: 'System detected the data source containing non-Kylin, it is recommended to delete the file.', id: 'NON_KYLIN_SOURCE' },
  EXCEED_FILE_LIMITED: { defaultMessage: 'The file size cannot exceed {fileLimit}.', id: 'EXCEED_FILE_LIMITED' },
  // Form Login
  PLEASE_ENTER_USERNAME: { defaultMessage: 'Please enter username.', id: 'PLEASE_ENTER_USERNAME' },
  PLEASE_ENTER_PASSWORD: { defaultMessage: 'Please enter password.', id: 'PLEASE_ENTER_PASSWORD' },
  FORGET_PASSWORD_TIP: { defaultMessage: 'Kylin MDX use the same user credential as Kylin, for ADMIN user account, you will need to reset Kylin password to initial password using command "kylin.sh admin-password-reset" in the "$KYLIN_HOME/bin" folder. For other users please contact your system administrator for password rest.', id: 'FORGET_PASSWORD_TIP' },
  // Dataset App
  HIERARCHY: { defaultMessage: 'Hierarchy', id: 'HIERARCHY' },
  NAMEDSET: { defaultMessage: 'Named Set', id: 'NAMEDSET' },
  NAMEDSETS: { defaultMessage: 'Named Sets', id: 'NAMEDSETS' },
  DIMENSION: { defaultMessage: 'Dimension', id: 'DIMENSION' },
  DIMENSIONS: { defaultMessage: 'Dimensions', id: 'DIMENSIONS' },
  MEASURE: { defaultMessage: 'Measure', id: 'MEASURE' },
  MEASURES: { defaultMessage: 'Measures', id: 'MEASURES' },
  CALCULATED_MEASURE: { defaultMessage: 'Calculated Measure', id: 'CALCULATED_MEASURE' },
  CALCULATED_MEASURES: { defaultMessage: 'Calculated Measures', id: 'CALCULATED_MEASURES' },
  REGULAR: { defaultMessage: 'Regular', id: 'REGULAR' },
  TIME: { defaultMessage: 'Time', id: 'TIME' },
  VISIBLE: { defaultMessage: 'Visible', id: 'VISIBLE' },
  VISIBILITY_TIP: { defaultMessage: 'Determines the visibility of it in client applications.', id: 'VISIBILITY_TIP' },
  CONFIRM_INVISIBLE_DATASET: { defaultMessage: 'If disabled, the {itemType} [{itemName}] cannot be analyzed in the client applications. Besides, the visibility restrictions of the {itemType} will be removed in the following step. Please confirm whether to disable.', id: 'CONFIRM_INVISIBLE_DATASET' },
  DATASET_UPGRADE_1_1_4: { defaultMessage: 'Starting from version 1.1.4, we have optimized the metadata structure of the dataset. You need to click this button to upgrade the metadata of all datasets.', id: 'DATASET_UPGRADE_1_1_4' },
  // Entity Access
  ENTITY_ACCESS_TITLE: { defaultMessage: '{entity} [{name}] Access Control', id: 'ENTITY_ACCESS_TITLE' },
  // Dataset App: Layout
  BASIC_INFORMATION: { defaultMessage: 'Basic Information', id: 'BASIC_INFORMATION' },
  DEFINE_RELATIONSHIPS: { defaultMessage: 'Define Relationships', id: 'DEFINE_RELATIONSHIPS' },
  DEFINE_SEMANTICS: { defaultMessage: 'Define Semantics', id: 'DEFINE_SEMANTICS' },
  TRANSLATION: { defaultMessage: 'Translation', id: 'TRANSLATION' },
  DIMENSION_USAGE: { defaultMessage: 'Dimension Usage', id: 'DIMENSION_USAGE' },
  ACCESS_LIST: { defaultMessage: 'Access List', id: 'ACCESS_LIST' },
  DEFINE_RELATIONSHIPS_TIP: { defaultMessage: 'Add 1 or multiple models and define the relationships, for the following semantic settings.', id: 'DEFINE_RELATIONSHIPS_TIP' },
  DEFINE_SEMANTICS_TIP: { defaultMessage: 'Add hierarchies, namedsets, and calculated measures to enrich the analysis capability of this dataset.', id: 'DEFINE_SEMANTICS_TIP' },
  TRANSLATION_TIP: { defaultMessage: 'Define translations that let users view/query the dataset in the language of their choice in client applications.', id: 'TRANSLATION_TIP' },
  DIMENSION_USAGE_TIP: { defaultMessage: 'Define relationships between dimension tables and measures, including "Unable to link", "Regular" and "Many-to-Many" relationships.', id: 'DIMENSION_USAGE_TIP' },
  ACCESS_LIST_TIP: { defaultMessage: 'Grant or restrict access to this dataset to ensure data security.', id: 'ACCESS_LIST_TIP' },
  CONFIRM_FIX_MODEL: { defaultMessage: 'Please fix the errors on this page and try again.', id: 'CONFIRM_FIX_MODEL' },
  CONFIRM_ISOLATED_MODEL: { defaultMessage: 'Please note that there are {modelCount} models in the dataset that are not connected to any other model.', id: 'CONFIRM_ISOLATED_MODEL' },
  DATASET_NAME_DUPLICATE: { defaultMessage: 'The dataset name already exists.', id: 'DATASET_NAME_DUPLICATE' },
  NOT_VALID_FORM: { defaultMessage: 'The page information is incorrect, please check.', id: 'NOT_VALID_FORM' },
  NOT_VALID_RELATION: { defaultMessage: 'Not a valid relationship.', id: 'NOT_VALID_RELATION' },
  FAILED_SAVE: { defaultMessage: 'Sorry, it occured an error when saving.', id: 'FAILED_SAVE' },
  SAVE_DATASET_SUCCESS: { defaultMessage: 'Dataset {datasetName} is saved successfully.', id: 'SAVE_DATASET_SUCCESS' },
  INVALID_NAME_IN_DATASET: { defaultMessage: 'Name only support Chinese, English, numbers, spaces, _, -, %, (, ),?.', id: 'INVALID_NAME_IN_DATASET' },
  INVALID_FOLDER_IN_DATASET: { defaultMessage: 'Display folder name only supports Chinese, English, numbers and spaces.', id: 'INVALID_FOLDER_IN_DATASET' },
  INVALID_ALIAS_IN_DATASET: { defaultMessage: 'Alias only supports Chinese, English, numbers, spaces, _, -, %, (, ),?.', id: 'INVALID_ALIAS_IN_DATASET' },
  INVALID_NAMED_SET_NAME_IN_DATASET: { defaultMessage: 'Name only support Chinese, English, numbers, spaces, _, -, %, (, ).', id: 'INVALID_NAMED_SET_NAME_IN_DATASET' },
  RETURN_TO_EDIT: { defaultMessage: 'Return to edit', id: 'RETURN_TO_EDIT' },
  DATASET_LIST: { defaultMessage: 'Dataset List', id: 'DATASET_LIST' },
  NOT_FOUND_ENTITY: { defaultMessage: 'The {entity} has been deleted.', id: 'NOT_FOUND_ENTITY' },
  REDIRECT_AFTER_TIMER: { defaultMessage: 'After {time}, the system will automatically jump to {page}.', id: 'REDIRECT_AFTER_TIMER' },
  // Dataset App: Basic Form
  DATASET_TYPE: { defaultMessage: 'Dataset Type: ', id: 'DATASET_TYPE' },
  PROJECT_NAME: { defaultMessage: 'Project Name', id: 'PROJECT_NAME' },
  DATASET_NAME: { defaultMessage: 'Dataset Name', id: 'DATASET_NAME' },
  INPUT_DATASET_NAME: { defaultMessage: 'Please enter the name of dataset', id: 'INPUT_DATASET_NAME' },
  SELECT_PROJECT: { defaultMessage: 'Select Project', id: 'SELECT_PROJECT' },
  PLEASE_SELECT_DATASET_TYPE: { defaultMessage: 'Please select dataset type.', id: 'PLEASE_SELECT_DATASET_TYPE' },
  PLEASE_SELECT_PROJECT: { defaultMessage: 'Please select at least one project.', id: 'PLEASE_SELECT_PROJECT' },
  SHOULD_HAVE_DATASET_NAME: { defaultMessage: 'Dataset name should not be empty.', id: 'SHOULD_HAVE_DATASET_NAME' },
  DATASET_NAME_TOO_LONG: { defaultMessage: 'Dataset name length cannot be greater than {maxLength}.', id: 'DATASET_NAME_TOO_LONG' },
  // Dataset App: Relations
  CONFIRM_DELETE_MODEL: { defaultMessage: 'Are you sure to delete this model? If the model is deleted, the semantic information and permission information of the related dimension table and the shared dimension table will be cleared.', id: 'CONFIRM_DELETE_MODEL' },
  REMOVE_MODEL_SUCCESS: { defaultMessage: 'Remove model [{modelName}] successfully.', id: 'REMOVE_MODEL_SUCCESS' },
  NO_MODELS: { defaultMessage: 'No Models.', id: 'NO_MODEL' },
  CONFIRM_DELETE_RELATIONS: { defaultMessage: 'Are you sure you want to delete this relationship?', id: 'CONFIRM_DELETE_RELATIONS' },
  DRAG_TO_ADD_MODEL: { defaultMessage: 'Drag models here to add and associate models.', id: 'DRAG_TO_ADD_MODEL' },
  MODEL_DELETED: { defaultMessage: 'Model [{modelName}] does not exist, please check the model in Kylin.', id: 'MODEL_DELETED' },
  HIERARCHY_DIM_COL_DELETED: { defaultMessage: 'Dimension [{modelName}].[{tableName}].[{columnName}] does not exist, please check the model in Kylin.', id: 'HIERARCHY_DIM_COL_DELETED' },
  PLEASE_REPAIRE_MODELS: { defaultMessage: 'After deleting or repairing the problem model, you can edit the model relationship.', id: 'PLEASE_REPAIRE_MODELS' },
  // Dataset App: Add Dataset Relationship Modal
  DUPLICATE_RELATIONSHIP: { defaultMessage: 'You can not add duplicate relationship.', id: 'DUPLICATE_RELATIONSHIP' },
  CONFIRM_UPDATE_RELATION: { defaultMessage: 'A shared dimension table is added, the semantic information and permission information of the original dimension table will be cleared.', id: 'CONFIRM_UPDATE_RELATION' },
  SELECT_FROM_MODEL: { defaultMessage: 'From Model', id: 'SELECT_FROM_MODEL' },
  SELECT_LOOKUP_MODEL: { defaultMessage: 'Lookup Model', id: 'SELECT_LOOKUP_MODEL' },
  CURRENT_MODEL: { defaultMessage: 'Current Model', id: 'CURRENT_MODEL' },
  RELATED_MODEL: { defaultMessage: 'Lookup Model', id: 'RELATED_MODEL' },
  SELECT_TABLE: { defaultMessage: 'Please select dimension table', id: 'SELECT_TABLE' },
  TABLE: { defaultMessage: 'Table', id: 'TABLE' },
  ADD_RELATED_MODEL: { defaultMessage: 'Add Lookup Model', id: 'ADD_RELATED_MODEL' },
  COMMON_TABLE_DELETED: { defaultMessage: 'Table [{tableName}] does not exist, please check the model in Kylin.', id: 'COMMON_TABLE_DELETED' },
  PLEASE_SELECT_TABLE: { defaultMessage: 'Please select the table.', id: 'PLEASE_SELECT_TABLE' },
  // Dataset App: Semantic
  TIPS: { defaultMessage: 'Tips', id: 'TIPS' },
  SEMANTIC_NOTICE_WARN: { defaultMessage: 'On this page, you could complete the following operations', id: 'SEMANTIC_NOTICE_WARN' },
  SEMANTIC_WELCOME_1: { defaultMessage: '1. Click on the dimension table name to change the dimension table properties', id: 'SEMANTIC_WELCOME_1' },
  SEMANTIC_WELCOME_2: { defaultMessage: '2. Click on the dimension name to change the dimension properties', id: 'SEMANTIC_WELCOME_2' },
  SEMANTIC_WELCOME_3: { defaultMessage: '3. Click on the measure name to change the measure properties', id: 'SEMANTIC_WELCOME_3' },
  SEMANTIC_WELCOME_4: { defaultMessage: '4. Click the {button} button to create a hierarchy', id: 'SEMANTIC_WELCOME_4' },
  SEMANTIC_WELCOME_5: { defaultMessage: '5. Click the {button} button to create a named set', id: 'SEMANTIC_WELCOME_5' },
  SEMANTIC_WELCOME_6: { defaultMessage: '6. Click the {button} button to create a calculated measure', id: 'SEMANTIC_WELCOME_6' },
  INVALID_NAME_IS_KEY_WORD: { defaultMessage: '[{name}] is a keyword and cannot be specified as the name of {nodeType}.', id: 'INVALID_NAME_IS_KEY_WORD' },
  FIX_DATASET_MESSAGE: { defaultMessage: 'The system found {entities} that can’t be resolved. Click here to {fixIt}.', id: 'FIX_DATASET_MESSAGE' },
  FIX_DATASET_CM: { defaultMessage: '{count, plural, one {# calculated measure} other {# calculated measures}}', id: 'FIX_DATASET_CM' },
  FIX_DATASET_NS: { defaultMessage: '{count, plural, one {# named set} other {# named sets}}', id: 'FIX_DATASET_NS' },
  FIX_DATASET_HI: { defaultMessage: '{count, plural, one {# hierarchy} other {# hierarchies}}', id: 'FIX_DATASET_HI' },
  FIX_IT: { defaultMessage: 'Fix It', id: 'FIX_IT' },
  // Dataset App: DimensionTableBlock
  SHOW_DIMENSION_TABLE_INFO: { defaultMessage: 'Show Dimension Table Properties', id: 'SHOW_DIMENSION_TABLE_INFO' },
  TABLE_NAME: { defaultMessage: 'Table Name', id: 'TABLE_NAME' },
  DIMENSION_TABLE_NAME: { defaultMessage: 'Dimension Table Name', id: 'DIMENSION_TABLE_NAME' },
  ATTRIBUTE: { defaultMessage: 'Attribute', id: 'ATTRIBUTE' },
  TYPE_DESC_FOR_TABLE: { defaultMessage: 'With time type being set, the table can be used for time-related calculations. E.g. YTD, YOY, etc.', id: 'TYPE_DESC_FOR_TABLE' },
  TYPE_DESC_FOR_COLUMN: { defaultMessage: 'With the corresponding time type being set, the dimension can be used for time-related calculations. E.g. YTD, YOY, etc.', id: 'TYPE_DESC_FOR_COLUMN' },
  PLEASE_ENTER_TABLE_ALIAS: { defaultMessage: 'Please enter table alias.', id: 'PLEASE_ENTER_TABLE_ALIAS' },
  PLEASE_SELECT_TYPE: { defaultMessage: 'Please select table attribute.', id: 'PLEASE_SELECT_TYPE' },
  TABLE_NAME_DUPLICATE: { defaultMessage: 'The dimension table named [{tableAlias}] already exists.', id: 'TABLE_NAME_DUPLICATE' },
  DIM_TABLE_NAME_TOO_LONG: { defaultMessage: 'Dimension table name length cannot be greater than {maxLength}.', id: 'DIM_TABLE_NAME_TOO_LONG' },
  SUCCESS_SUBMIT_DIMENSION_TABLE: { defaultMessage: 'Submit dimension table [{tableAlias}] successfully.', id: 'SUCCESS_SUBMIT_DIMENSION_TABLE' },
  CONFIRM_DIM_TABLE_CHANGE_TYPE_HAS_WEIGHT: { defaultMessage: 'The weight setting will not take effect on the dimension table of the time type. Are you sure you want to set to time type?', id: 'CONFIRM_DIM_TABLE_CHANGE_TYPE_HAS_WEIGHT' },
  // Dataset App: DimensionColumnBlock
  SHOW_DIMENSION: { defaultMessage: 'Show Dimension', id: 'SHOW_DIMENSION' },
  EDIT_DIMENSION: { defaultMessage: 'Edit Dimension', id: 'EDIT_DIMENSION' },
  KEY_COLUMN: { defaultMessage: 'Column Name (Key Column)', id: 'KEY_COLUMN' },
  DIMENSION_NAME: { defaultMessage: 'Dimension Name', id: 'DIMENSION_NAME' },
  DATA_TYPE: { defaultMessage: 'Data Type', id: 'DATA_TYPE' },
  NAME_COLUMN: { defaultMessage: 'Name Column', id: 'NAME_COLUMN' },
  NAME_COLUMN_DESC: { defaultMessage: 'The Name Column will be displayed in the client applications.', id: 'NAME_COLUMN_DESC' },
  VALUE_COLUMN: { defaultMessage: 'Value Column', id: 'VALUE_COLUMN' },
  VALUE_COLUMN_DESC: { defaultMessage: 'With the Value Column being defined, the MemberValue function can be used in the expression of the calculated measure to return the specified column.', id: 'VALUE_COLUMN_DESC' },
  PROPERTIES: { defaultMessage: 'Properties', id: 'PROPERTIES' },
  PROPERTIES_DESC: { defaultMessage: 'With the Properties being defined, the Properties function can be used in the expression of the calculated measure to return the specified column.', id: 'PROPERTIES_DESC' },
  LEVEL_YEAR: { defaultMessage: 'Year', id: 'LEVEL_YEAR' },
  LEVEL_QUARTERS: { defaultMessage: 'Quarter', id: 'LEVEL_QUARTERS' },
  LEVEL_MONTHS: { defaultMessage: 'Month', id: 'LEVEL_MONTHS' },
  LEVEL_WEEKS: { defaultMessage: 'Week', id: 'LEVEL_WEEKS' },
  LEVEL_DAYS: { defaultMessage: 'Day', id: 'LEVEL_DAYS' },
  DIMENSION_NAME_DUPLICATE: { defaultMessage: 'The dimension named [{columnAlias}] already exists.', id: 'DIMENSION_NAME_DUPLICATE' },
  DIMENSION_NAME_TOO_LONG: { defaultMessage: 'The dimension name length cannot be greater than {maxLength}.', id: 'DIMENSION_NAME_TOO_LONG' },
  SUCCESS_SUBMIT_DIMENSION: { defaultMessage: 'Submit dimension [{columnName}] successfully.', id: 'SUCCESS_SUBMIT_DIMENSION' },
  NAME_COLUMN_DIM_COL_DELETED: { defaultMessage: 'Column [{modelName}].[{tableAlias}].[{columnName}] does not exist, please check the model in Kylin.', id: 'NAME_COLUMN_DIM_COL_DELETED' },
  VALUE_COLUMN_DIM_COL_DELETED: { defaultMessage: 'Column [{modelName}].[{tableAlias}].[{columnName}] does not exist, please check the model in Kylin.', id: 'VALUE_COLUMN_DIM_COL_DELETED' },
  INVALID_DEFAULT_MEMBER_EXPRESSION: { defaultMessage: 'The default member can only be set as a member of this dimension, for example [Dates].[Year].&[2019].', id: 'INVALID_DEFAULT_MEMBER_EXPRESSION' },
  PROPERTY_COLUMN_DIM_COL_DELETED: { defaultMessage: 'Dimension [{modelName}].[{tableAlias}].[{columnName}] does not exist, please check the model in Kylin.', id: 'PROPERTY_COLUMN_DIM_COL_DELETED' },
  PROPERTY_TOTAL_COLUMN_DELETED: { defaultMessage: 'The following dimension(s) do not exist, please check the model in Kylin:', id: 'PROPERTY_TOTAL_COLUMN_DELETED' },
  NAME_COLUMN_TIP: { defaultMessage: 'To ensure the accuracy of query results, the value in Name Column must have the one-to-one mapping relationship with the value in Key Column.', id: 'NAME_COLUMN_TIP' },
  VALUE_COLUMN_TIP: { defaultMessage: 'To ensure the accuracy of query results, the value in Value Column must have a one-to-one or one-to-many mapping relationship with the value in Key Column.', id: 'VALUE_COLUMN_TIP' },
  PROPERTIES_TIP: { defaultMessage: 'To ensure the accuracy of query results, the value in each property must have a one-to-one or one-to-many mapping relationship with the value in Key Column.', id: 'PROPERTIES_TIP' },
  DEFAULT_MEMBER: { defaultMessage: 'Default Member', id: 'DEFAULT_MEMBER' },
  DEFAULT_MEMBER_DESC: { defaultMessage: 'Use an expression to specify a single default member returned by this dimension.', id: 'DEFAULT_MEMBER_DESC' },
  DEFAULT_MEMBER_TOO_LONG: { defaultMessage: 'The default member length cannot be greater than {maxLength}.', id: 'DEFAULT_MEMBER_TOO_LONG' },
  // Dataset App: HierarchyBlock
  ADD_HIERARCHY: { defaultMessage: 'Add Hierarchy', id: 'ADD_HIERARCHY' },
  EDIT_HIERARCHY: { defaultMessage: 'Edit Hierarchy', id: 'EDIT_HIERARCHY' },
  SHOW_HIERARCHY: { defaultMessage: 'Show Hierarchy', id: 'SHOW_HIERARCHY' },
  MODEL_TABLE: { defaultMessage: 'Model / Table', id: 'MODEL_TABLE' },
  SEARCH_MODEL_TABLE: { defaultMessage: 'Please select the table where you need to create a hierarchy dimension.', id: 'SEARCH_MODEL_TABLE' },
  COLUMN_LOST_IN_KE: { defaultMessage: '{lostColumns} do not exist, please check the model in Kylin.', id: 'COLUMN_LOST_IN_KE' },
  HIERARCHY_DUPLICATE: { defaultMessage: 'The hierarchy named [{hierarchyName}] already exists.', id: 'HIERARCHY_DUPLICATE' },
  HIERARCHY_NAME_TOO_LONG: { defaultMessage: 'Hierarchy name length cannot be greater than {maxLength}.', id: 'HIERARCHY_NAME_TOO_LONG' },
  PLEASE_SELECT_MODEL_TABLE: { defaultMessage: 'Please select the table where you need to create a hierarchy dimension.', id: 'PLEASE_SELECT_MODEL_TABLE' },
  TOW_MORE_DIMENSIONS: { defaultMessage: 'Please select 2 or more dimensions.', id: 'TOW_MORE_DIMENSIONS' },
  HIERARCHY_COLUMNS_DELETED: { defaultMessage: 'Dimension {deletedCols} does not exist, please check the model in Kylin.', id: 'HIERARCHY_COLUMNS_DELETED' },
  CONFIRM_DELETE_HIERARCHY: { defaultMessage: 'Are you sure to delete Hierarchy [{hierarchyName}]?', id: 'CONFIRM_DELETE_HIERARCHY' },
  SUCCESS_DELETE_HIERARCHY: { defaultMessage: 'Hierarchy [{hierarchyName}] is deleted successfully.', id: 'SUCCESS_DELETE_HIERARCHY' },
  SUCCESS_SUBMIT_HIERARCHY: { defaultMessage: 'Submit hierarchy [{hierarchyName}] successfully.', id: 'SUCCESS_SUBMIT_HIERARCHY' },
  SET_WEIGHT: { defaultMessage: 'Set Weight', id: 'SET_WEIGHT' },
  HIERARCHY_WEIGHT_TIP: { defaultMessage: 'When calculating the value of the level dimension, the weight column will be multiplied by the value of the dimension member. This setting is for defining how member values are rolled up into parent values in a hierarchy.', id: 'HIERARCHY_WEIGHT_TIP' },
  WEIGHT_COLUMN: { defaultMessage: 'Weight Column', id: 'WEIGHT_COLUMN' },
  // Dataset App: NamedSetBlock
  ADD_NAMEDSET: { defaultMessage: 'Add Named Set', id: 'ADD_NAMEDSET' },
  EDIT_NAMEDSET: { defaultMessage: 'Edit Named Set', id: 'EDIT_NAMEDSET' },
  SHOW_NAMEDSET: { defaultMessage: 'Show Named Set', id: 'SHOW_NAMEDSET' },
  EXPRESSION: { defaultMessage: 'Expression', id: 'EXPRESSION' },
  EXPRESSION_DESC: { defaultMessage: 'Use an expression to specify a set of dimension members returned.', id: 'EXPRESSION_DESC' },
  LOCATION: { defaultMessage: 'Location', id: 'LOCATION' },
  NAMEDSET_EXPRESSION_TIP: { defaultMessage: 'A valid, MDX expression as supported by the underlying backend. Example: [Reseller].[Reseller Name].[Reseller Name].Members', id: 'NAMEDSET_EXPRESSION_TIP' },
  NAMEDSET_EXPRESSION_TOO_LONG: { defaultMessage: 'The named set expression length cannot be greater than {maxLength}.', id: 'NAMEDSET_EXPRESSION_TOO_LONG' },
  NAMEDSET_DUPLICATE: { defaultMessage: 'The named set named [{namedSetName}] already exists in whole dataset.', id: 'NAMEDSET_DUPLICATE' },
  NAMEDSET_NAME_TOO_LONG: { defaultMessage: 'The named set name length cannot be greater than {maxLength}.', id: 'NAMEDSET_NAME_TOO_LONG' },
  PLEASE_SELECT_LOCATION: { defaultMessage: 'Please select location.', id: 'PLEASE_SELECT_LOCATION' },
  PLEASE_ENTER_EXPRESSION: { defaultMessage: 'Expression could not be empty.', id: 'PLEASE_ENTER_EXPRESSION' },
  CONFIRM_DELETE_NAMEDSET: { defaultMessage: 'Are you sure to delete named set [{namedSetName}]?', id: 'CONFIRM_DELETE_NAMEDSET' },
  SUCCESS_DELETE_NAMEDSET: { defaultMessage: 'Named set [{namedSetName}] is deleted successfully.', id: 'SUCCESS_DELETE_NAMEDSET' },
  SUCCESS_SUBMIT_NAMEDSET: { defaultMessage: 'Submit named set [{namedSetName}] successfully.', id: 'SUCCESS_SUBMIT_NAMEDSET' },
  // Dataset App: DimensionMeasureBlock
  EDIT_MEASURE: { defaultMessage: 'Edit Measure', id: 'EDIT_MEASURE' },
  SHOW_MEASURE: { defaultMessage: 'Show Measure', id: 'SHOW_MEASURE' },
  METRIC_TYPE: { defaultMessage: 'Metric Type', id: 'METRIC_TYPE' },
  MEASURE_DUPLICATE: { defaultMessage: 'The measure named [{measureName}] already exists.', id: 'MEASURE_DUPLICATE' },
  MEASURE_NAME_TOO_LONG: { defaultMessage: 'The measure name length cannot be greater than {maxLength}.', id: 'MEASURE_NAME_TOO_LONG' },
  SUCCESS_SUBMIT_MEASURE: { defaultMessage: 'Submit measure [{measureName}] successfully.', id: 'SUCCESS_SUBMIT_MEASURE' },
  // Dataset App: CalculateMeasureBlock
  ADD_CALCULATED_MEASURE: { defaultMessage: 'Add Calculated Measure', id: 'ADD_CALCULATED_MEASURE' },
  EDIT_CALCULATED_MEASURE: { defaultMessage: 'Edit Calculated Measure', id: 'EDIT_CALCULATED_MEASURE' },
  SHOW_CALCULATED_MEASURE: { defaultMessage: 'Show Calculated Measure', id: 'SHOW_CALCULATED_MEASURE' },
  FORMAT: { defaultMessage: 'Format', id: 'FORMAT' },
  FORMAT_DESC: { defaultMessage: 'The default format shown in the client application.', id: 'FORMAT_DESC' },
  MDX_DEFAULT_MEMBER_TIP: { defaultMessage: 'Please notice this feature is still in BETA phase.', id: 'MDX_DEFAULT_MEMBER_TIP' },
  MDX_EXPRESSION_TIP: { defaultMessage: 'A valid, MDX expression as supported by the underlying backend. Example: [Measures].[Discount Amount] * 1.5', id: 'MDX_EXPRESSION_TIP' },
  CALCULATE_MEASURE_DUPLICATE: { defaultMessage: 'The calculated measure named [{cMeasureName}] already exists in whole dataset.', id: 'CALCULATE_MEASURE_DUPLICATE' },
  CMEASURE_NAME_TOO_LONG: { defaultMessage: 'The calculated measure name length cannot be greater than {maxLength}.', id: 'CMEASURE_NAME_TOO_LONG' },
  FOLDER_NAME_TOO_LONG: { defaultMessage: 'Display folder cannot exceed {maxLength} characters.', id: 'FOLDER_NAME_TOO_LONG' },
  PLEASE_ENTER_FORMAT: { defaultMessage: 'Please select or enter a format string, such as #,###.', id: 'PLEASE_ENTER_FORMAT' },
  PLEASE_SELECT_MEASURE_GROUP: { defaultMessage: 'Please select measure group.', id: 'PLEASE_SELECT_MEASURE_GROUP' },
  CMEASURE_EXPRESSION_TOO_LONG: { defaultMessage: 'The calculated measure expression length cannot be greater than {maxLength}.', id: 'CMEASURE_EXPRESSION_TOO_LONG' },
  CONFIRM_DELETE_CMEASURE: { defaultMessage: 'Are you sure to delete calculated measure [{cMeasureName}]?', id: 'CONFIRM_DELETE_CMEASURE' },
  SUCCESS_DELETE_CMEASURE: { defaultMessage: 'Calculated measure [{cMeasureName}] is deleted successfully.', id: 'SUCCESS_DELETE_CMEASURE' },
  SUCCESS_SUBMIT_CMEASURE: { defaultMessage: 'Submit calculated measure [{cMeasureName}] successfully.', id: 'SUCCESS_SUBMIT_CMEASURE' },
  NON_EMPTY_BEHAVIOR_DELETED: { defaultMessage: 'Measure [Measures].[{alias}] does not exist, please check the model in Kylin.', id: 'NON_EMPTY_BEHAVIOR_DELETED' },
  // Dataset App: FolderInput
  FOLDER: { defaultMessage: 'Folder', id: 'FOLDER' },
  FOLDER_DESC: { defaultMessage: 'The folder hierarchy will be displayed in client application.{example}', id: 'FOLDER_DESC' },
  FOLDER_DESC_EXAMPLE: { defaultMessage: 'E.g. in Excel it will be shown as:{folderTree}', id: 'FOLDER_DESC_EXAMPLE' },
  FOLDER_EXAMPLE_1: { defaultMessage: 'Important concern', id: 'FOLDER_EXAMPLE_1' },
  FOLDER_EXAMPLE_2: { defaultMessage: 'High importance', id: 'FOLDER_EXAMPLE_2' },
  FOLDER_NAME_TIP: { defaultMessage: 'Support Chinese, English, numbers. Use \\ character to create hierarchical folders, e.g. AAA\\BBB.', id: 'FOLDER_NAME_TIP' },
  FOLDER_PREVIEW: { defaultMessage: 'Folder Preview', id: 'FOLDER_PREVIEW' },
  RECENTLY_USED: { defaultMessage: 'Recently Used', id: 'RECENTLY_USED' },
  NO_FOLDER: { defaultMessage: 'No folder', id: 'NO_FOLDER' },
  NO_RECENTLY_USED: { defaultMessage: 'No recently used', id: 'NO_RECENTLY_USED' },
  // Dataset App: MeasureGroupBlock
  EDIT_MEASURE_GROUP: { defaultMessage: 'Edit Model', id: 'EDIT_MEASURE_GROUP' },
  SHOW_MEASURE_GROUP: { defaultMessage: 'Show Model', id: 'SHOW_MEASURE_GROUP' },
  MEASURE_GROUP: { defaultMessage: 'Measure Group', id: 'MEASURE_GROUP' },
  MEASURE_GROUP_DESC: { defaultMessage: 'The name of measure group shown in the client applications.', id: 'MEASURE_GROUP_DESC' },
  NON_EMPTY_BEHAVIOR: { defaultMessage: 'Non-empty behavior', id: 'NON_EMPTY_BEHAVIOR' },
  NON_EMPTY_BEHAVIOR_TIP: { defaultMessage: 'If one or more measures are specified in this property, and all the measures are empty, the calculated measure will be directly regarded as empty. If this property is left empty, calculations must be performed to determine whether the calculated measure is empty.', id: 'NON_EMPTY_BEHAVIOR_TIP' },
  SUCCESS_SUBMIT_MODEL: { defaultMessage: 'Submit model [{measureGroupName}] successfully.', id: 'SUCCESS_SUBMIT_MODEL' },
  PLEASE_ENTER_MEASURE_GROUP_NAME: { defaultMessage: 'Please enter measure group name.', id: 'PLEASE_ENTER_MEASURE_GROUP_NAME' },
  MEASURE_GROUP_NAME_DUPLICATE: { defaultMessage: 'The measure group named [{measureGroupName}] already exists.', id: 'MEASURE_GROUP_NAME_DUPLICATE' },
  MEASURE_GROUP_NAME_TOO_LONG: { defaultMessage: 'The measure group name length cannot be greater than {maxLength}.', id: 'MEASURE_GROUP_NAME_TOO_LONG' },
  // Dataset App: DatasetTranslation
  DEFAULT_TRANSLATION: { defaultMessage: 'Default Language', id: 'DEFAULT_TRANSLATION' },
  OBJECT_TYPE: { defaultMessage: 'Object Type', id: 'OBJECT_TYPE' },
  ADD_TRANSLATION: { defaultMessage: 'Add Language', id: 'ADD_TRANSLATION' },
  DELETE_TRANSLATION: { defaultMessage: 'Delete Language', id: 'DELETE_TRANSLATION' },
  TRANSLATION_UP_TO_MAX: { defaultMessage: 'All translation languages have been added.', id: 'TRANSLATION_UP_TO_MAX' },
  CONFIRM_DELETE_TRANSLATION: { defaultMessage: 'Do you want to delete the language "{translationText}"?', id: 'CONFIRM_DELETE_TRANSLATION' },
  CONFIRM_DELETE_TRANSLATION_TIP: { defaultMessage: 'Are you sure you want to delete the language "{translationText}"? The language displayed in the client applications might be affected.', id: 'CONFIRM_DELETE_TRANSLATION_TIP' },
  SUCCESS_DELETE_TRANSLATION: { defaultMessage: 'The language [{translationText}] is deleted successfully.', id: 'SUCCESS_DELETE_TRANSLATION' },
  /* disable-explore-chinese-next-line */
  'zh-CN': { defaultMessage: '中文(简体)', id: 'zh-CN' },
  'en-UK': { defaultMessage: 'English(UK)', id: 'en-UK' },
  'en-US': { defaultMessage: 'English(US)', id: 'en-US' },
  WARN_FIX_TRANSLATION: { defaultMessage: 'Please fix or delete the wrong Caption translation before proceeding.', id: 'WARN_FIX_TRANSLATION' },
  INVALID_TRANSLATION_IN_DATASET: { defaultMessage: 'Translation of caption only supports Chinese, English, numbers, spaces, _, -, %, (, ),?.', id: 'INVALID_TRANSLATION_IN_DATASET' },
  TRANSLATION_TOO_LONG: { defaultMessage: 'Translation length of caption cannot be greater than {maxLength}.', id: 'TRANSLATION_TOO_LONG' },
  // Dataset App: DatasetUsages
  DIMENSION_TABLES: { defaultMessage: 'Dimension Tables', id: 'DIMENSION_TABLES' },
  DIMENSION_TABLE: { defaultMessage: 'Dimension Table', id: 'DIMENSION_TABLE' },
  PUBLIC_DIMENSION_TABLE: { defaultMessage: 'Public dimension table', id: 'PUBLIC_DIMENSION_TABLE' },
  MODEL_NAME: { defaultMessage: 'Model Name', id: 'MODEL_NAME' },
  JOINT: { defaultMessage: 'Regular', id: 'JOINT' },
  NOT_JOINT: { defaultMessage: 'No Link', id: 'NOT_JOINT' },
  MANY_TO_MANY: { defaultMessage: 'Many-to-Many', id: 'MANY_TO_MANY' },
  UNABLE_TO_LINK: { defaultMessage: 'Unable to link', id: 'UNABLE_TO_LINK' },
  // Dataset App: DimensionUsageModal
  DEFINE_DIMENSION_USAGE: { defaultMessage: 'Define Dimension Usage', id: 'DEFINE_DIMENSION_USAGE' },
  DEDUPLICATE_BY_THIS_COLUMN: { defaultMessage: 'Deduplicate by this column', id: 'DEDUPLICATE_BY_THIS_COLUMN' },
  DEDUPLICATE_BY_THIS_COLUMN_DESC: { defaultMessage: 'The primary key of the fact table in this model.', id: 'DEDUPLICATE_BY_THIS_COLUMN_DESC' },
  INTERMEDIATE_TABLE: { defaultMessage: 'Intermediate table', id: 'INTERMEDIATE_TABLE' },
  INTERMEDIATE_TABLE_DESC: { defaultMessage: 'The intermediate fact table (or called the bridge table), which links this dimension table to a dimension or fact table in the model.', id: 'INTERMEDIATE_TABLE_DESC' },
  RELATIONSHIP_ERROR_FACT_KEY: { defaultMessage: 'There are no dimension columns in the fact table, so the relationship cannot be established.', id: 'RELATIONSHIP_ERROR_FACT_KEY' },
  PLEASE_SELECT_FACT_KEY: { defaultMessage: 'Please select deduplicate column.', id: 'PLEASE_SELECT_FACT_KEY' },
  DIM_COL_DELETED: { defaultMessage: 'Dimension [{modelName}].[{tableName}].[{columnName}] does not exist, please check the model in Kylin.', id: 'DIM_COL_DELETED' },
  RELATIONSHIP_ERROR_TABLE: { defaultMessage: 'There is no intermediate table, so the relationship cannot be established.', id: 'RELATIONSHIP_ERROR_TABLE' },
  PLEASE_SELECT_INTERMEDIATE_TABLE: { defaultMessage: 'Please select intermediate table.', id: 'PLEASE_SELECT_INTERMEDIATE_TABLE' },
  BRIDGE_TABLE_DELETED: { defaultMessage: 'Table [{modelName}].[{tableName}] does not exist, please check the model in Kylin.', id: 'BRIDGE_TABLE_DELETED' },
  JOINT_TIP: { defaultMessage: 'The dimension table is directly linked to the model.', id: 'JOINT_TIP' },
  NOT_JOINT_TIP: { defaultMessage: 'The dimension table is independent of the measures in the model.', id: 'NOT_JOINT_TIP' },
  MANY_TO_MANY_TIP: { defaultMessage: 'The dimension table is joined to an intermediate fact table. The intermediate fact table is joined to a dimension table to which the fact table is joined.', id: 'MANY_TO_MANY_TIP' },
  // Dataset App: DatasetAccess
  USER_OR_GROUP_OR_ROLE: { defaultMessage: 'User / Group / Role', id: 'USER_OR_GROUP_OR_ROLE' },
  SEARCH_USER_OR_ROLE: { defaultMessage: 'Search User / Role', id: 'SEARCH_USER_OR_ROLE' },
  MEASURE_NAME: { defaultMessage: 'Measure Name', id: 'MEASURE_NAME' },
  CALCULATED_MEASURE_NAME: { defaultMessage: 'Calculated Measure Name', id: 'CALCULATED_MEASURE_NAME' },
  NAMEDSET_NAME: { defaultMessage: 'Named Set Name', id: 'NAMEDSET_NAME' },
  DIMENSIONS_ACCESS_LIST: { defaultMessage: 'Dimensions Access List', id: 'DIMENSIONS_ACCESS_LIST' },
  MEASURES_ACCESS_LIST: { defaultMessage: 'Measures Access List', id: 'MEASURES_ACCESS_LIST' },
  CMEASURES_ACCESS_LIST: { defaultMessage: 'Calculated Measures Access List', id: 'CMEASURES_ACCESS_LIST' },
  NAMED_SET_ACCESS_LIST: { defaultMessage: 'Named Set Access List', id: 'NAMED_SET_ACCESS_LIST' },
  CONFIRM_DELETE_ACCESS_LIST: { defaultMessage: 'Are you sure to delete access rights configuration for {restrictType} [{restrictRecord}]?', id: 'CONFIRM_DELETE_ACCESS_LIST' },
  SUCCESS_DELETE_ACCESS_LIST: { defaultMessage: 'Access rights configuration for {restrictType} [{restrictRecord}] is deleted successfully.', id: 'SUCCESS_DELETE_ACCESS_LIST' },
  DATASET_ITEM_IS_VISIBLE_BY_DEFAULT: { defaultMessage: 'When unspecified, by default, users can access this dataset and {entities} in it.', id: 'DATASET_ITEM_IS_VISIBLE_BY_DEFAULT' },
  DATASET_ITEM_IS_INVISIBLE_BY_DEFAULT: { defaultMessage: 'When unspeficied, by default, users cannot access this dataset and {entities} in it.', id: 'DATASET_ITEM_IS_INVISIBLE_BY_DEFAULT' },
  GRANT: { defaultMessage: 'Grant', id: 'GRANT' },
  RESTRICT: { defaultMessage: 'Restrict', id: 'RESTRICT' },
  // Dataset App: DatasetAccessModal
  GRANT_ACCESS_FOR_ENTITY: { defaultMessage: 'Grant Access for {entity}', id: 'GRANT_ACCESS_FOR_ENTITY' },
  RESTRICT_ACCESS_FOR_ENTITY: { defaultMessage: 'Restrict Access for {entity}', id: 'RESTRICT_ACCESS_FOR_ENTITY' },
  SEARCH_DIMENSION_OR_COLUMN: { defaultMessage: 'Search dimension name', id: 'SEARCH_DIMENSION_OR_COLUMN' },
  SEARCH_MEASURE_NAME: { defaultMessage: 'Search measure name', id: 'SEARCH_MEASURE_NAME' },
  SEARCH_CMEASURE_NAME: { defaultMessage: 'Search calculated measure name', id: 'SEARCH_CMEASURE_NAME' },
  SEARCH_NAMEDSET_NAME: { defaultMessage: 'Search named set name', id: 'SEARCH_NAMEDSET_NAME' },
  ACCESS_LIST_TITLE_TIP: { defaultMessage: 'Here you can set up the access list for a user, group or role.', id: 'ACCESS_LIST_TITLE_TIP' },
  PLEASE_SELECT_ANY_VISIBLE_ACCESS: { defaultMessage: 'Dataset default access is invisible, please select at least one visible {nodeType}.', id: 'PLEASE_SELECT_ANY_VISIBLE_ACCESS' },
  PLEASE_SELECT_ANY_INVISIBLE_ACCESS: { defaultMessage: 'Dataset default access is visible, please select at least one invisible {nodeType}.', id: 'PLEASE_SELECT_ANY_INVISIBLE_ACCESS' },
  SAVE_VISIBILITY_RESTRICT_SUCCESSFULLY: { defaultMessage: 'Visibility Restrict for [{username}] is saved successfully.', id: 'SAVE_VISIBILITY_RESTRICT_SUCCESSFULLY' },
  DISABLED_COLUMN_IN_KE: { defaultMessage: 'The {type} has been restricted access to the column {effectedBy} referenced by this {nodeType}, access is automatically restricted and cannot be modified.', id: 'DISABLED_COLUMN_IN_KE' },
  DISABLED_TABLE_IN_KE: { defaultMessage: 'The {type} has been restricted access to the table {effectedBy} referenced by this {nodeType}, access is automatically restricted and cannot be modified.', id: 'DISABLED_TABLE_IN_KE' },
  DISABLED_COLUMN_VISIBILITY: { defaultMessage: 'The access of this {nodeType} is automatically restricted for all user and user group, because this {nodeType} has been confgured to be not visible. To change the setting, please turn the {nodeType} into visible on the {nodeType} setting.', id: 'DISABLED_COLUMN_VISIBILITY' },
  EMPTY_DATASET_ENTITY: { defaultMessage: 'There is no {entity} in this dataset', id: 'EMPTY_DATASET_ENTITY' },
  // ConnectionUserModal
  EDIT_CONNECTION_USER: { defaultMessage: 'Edit Connection User Info.', id: 'EDIT_CONNECTION_USER' },
  INIT_CONNECTION_USER: { defaultMessage: 'Configure Connection User Info.', id: 'INIT_CONNECTION_USER' },
  EDIT_CONNECTION_USER_TIP: { defaultMessage: 'Please enter the username and password of the Kylin system administrator.', id: 'EDIT_CONNECTION_USER_TIP' },
  // FixDatasetModal
  FIX_DATASET_MODAL_TITLE: { defaultMessage: 'Batch Delete', id: 'FIX_DATASET_MODAL_TITLE' },
  FIX_DATASET_MODAL_DESC: { defaultMessage: 'The system found {entities} that can\'t be resolved. Please select the ones you want to delete.', id: 'FIX_DATASET_MODAL_DESC' },
  INVALID_CM_NS_HI: { defaultMessage: 'Unresolved calculated measures/named sets/hierarchies', id: 'INVALID_CM_NS_HI' },
  CONFIRM_DELETE_UNRESOLVE_ITEMS: { defaultMessage: '{entities} have been selected. The delete action is irreversible. Please proceed with caution.', id: 'CONFIRM_DELETE_UNRESOLVE_ITEMS' },
  CONFIRM_DELETE_TITLE: { defaultMessage: 'Confirm Delete', id: 'CONFIRM_DELETE_TITLE' },
  PLEASE_SELECT_ITEM: { defaultMessage: 'Please select at least one item.', id: 'PLEASE_SELECT_ITEM' },
  // ExportDatasetModal
  EXPORT_DATASET_DESC: { defaultMessage: 'To ensure the file is undamaged, please don\'t unzip the file or modify the contents.', id: 'EXPORT_DATASET_DESC' },
  SCROLL_DOWN_LOAD_MROE: { defaultMessage: 'Scroll down to load more...', id: 'SCROLL_DOWN_LOAD_MROE' },
  CONFIRM_EXCEED_SIZE_TITLE: { defaultMessage: 'The size exceeds the recommended value', id: 'CONFIRM_EXCEED_SIZE_TITLE' },
  CONFIRM_EXCEED_SIZE_CONTENT: { defaultMessage: 'The total size of the data set you selected is {size}, which exceeds the recommended value, {fileLimit}. It could result in slow export and import. Please try to export them seperately.', id: 'CONFIRM_EXCEED_SIZE_CONTENT' },
  CONFIRM_EXPORT: { defaultMessage: 'Continue', id: 'CONFIRM_EXPORT' },
  BACK_TO_SELECT: { defaultMessage: 'Prev', id: 'BACK_TO_SELECT' },
  SELECT_DATASET: { defaultMessage: 'Choose dataset', id: 'SELECT_DATASET' },
  EXPORT_ERROR_DATASET_TITLE: { defaultMessage: 'Export Datasets in Error State', id: 'EXPORT_ERROR_DATASET_TITLE' },
  EXPORT_ERROR_DATASET_CONTENT: { defaultMessage: 'Please confirm if you want to export following datasets in error state.', id: 'EXPORT_ERROR_DATASET_CONTENT' },
  // UploadDatasetModal
  SELECT_UPLOAD_FILE: { defaultMessage: 'Upload File', id: 'SELECT_UPLOAD_FILE' },
  PARSE: { defaultMessage: 'Parse', id: 'PARSE' },
  // DifferDatasetsModal
  ADD_NEW: { defaultMessage: 'Add New', id: 'ADD_NEW' },
  REPLACE: { defaultMessage: 'Replace', id: 'REPLACE' },
  NOT_IMPORT: { defaultMessage: 'Not Import', id: 'NOT_IMPORT' },
  IMPORT_ACL: { defaultMessage: 'Import ACL', id: 'IMPORT_ACL' },
  RELATIONSHIP: { defaultMessage: 'Relationship', id: 'RELATIONSHIP' },
  SEMANTIC: { defaultMessage: 'Semantic', id: 'SEMANTIC' },
  NEW: { defaultMessage: 'New', id: 'NEW' },
  DIFFER_DATASET_DESC: { defaultMessage: '{number} datasets have been parsed successfully. {viewMore}', id: 'DIFFER_DATASET_DESC' },
  VIEW_IMPORT_RULES: { defaultMessage: 'View import rules.', id: 'VIEW_IMPORT_RULES' },
  IMPORT_RULE_1: { defaultMessage: 'When a dataset with the same name exists in the current project, it is recommended to replace this dataset.', id: 'IMPORT_RULE_1' },
  IMPORT_RULE_2: { defaultMessage: 'When a dataset’s name is different, it is recommended to create a new dataset.', id: 'IMPORT_RULE_2' },
  BRIFE_TREE_TIP: { defaultMessage: 'No dataset with the same name has been found in the current project.{br}It is recommended to add as a new one. The data set is as follows:', id: 'BRIFE_TREE_TIP' },
  DIFFER_TREE_TIP: { defaultMessage: 'A dataset with the same name has been found in the current project.{br}It is recommended to replace the current one. This data set has the following changes compared with the current dataset:', id: 'DIFFER_TREE_TIP' },
  DIFFER_TREE_SAME_TIP: { defaultMessage: 'A dataset with the same name has been found in the current project. It is recommended to replace the current one.{br}The two datasets with the same name is identical.', id: 'DIFFER_TREE_SAME_TIP' },
  IMPORT: { defaultMessage: 'Import', id: 'IMPORT' },
  CONFIRM_OVERRIDE_DATASETS_TITLE: { defaultMessage: 'Confirm Replace/Overwrite Action', id: 'CONFIRM_OVERRIDE_DATASETS_TITLE' },
  CONFIRM_OVERRIDE_DATASETS_DESC: { defaultMessage: 'Please confirm if you want to overwrite the following datasets. The overwrite action is irreversible. Please export those datasets as backups before you conduct this action.', id: 'CONFIRM_OVERRIDE_DATASETS_DESC' },
  CONFIRM_OVERRIDE: { defaultMessage: 'Confirm Overwrite', id: 'CONFIRM_OVERRIDE' },
  NO_INFORMATION_DISPLAY: { defaultMessage: 'No information display', id: 'NO_INFORMATION_DISPLAY' },
  RESET_DATASET_NAME: { defaultMessage: 'The system only supports overwriting datasets with the same name, so the dataset has been automatically restored to the original name.', id: 'RESET_DATASET_NAME' },
  CHANGED: { defaultMessage: 'Changed', id: 'CHANGED' },
  NO_CHANGE: { defaultMessage: 'No Change', id: 'NO_CHANGE' },
  DELETE_DATASETS_ERROR_TITLE: { defaultMessage: 'Import Dataset Action Failed Partly', id: 'DELETE_DATASETS_ERROR_TITLE' },
  DELETE_DATASETS_ERROR_DESC: { defaultMessage: 'The following dataset import failed, please try again.', id: 'DELETE_DATASETS_ERROR_DESC' },
  FAILED_IMPORT_DATASET: { defaultMessage: 'The datasets were imported failed.', id: 'FAILED_IMPORT_DATASET' },
  // AboutModal
  VERSION_C: { defaultMessage: 'Version:', id: 'VERSION_C' },
  VALID_PERIOD_C: { defaultMessage: 'Valid Period:', id: 'VALID_PERIOD_C' },
  SERVICE_END_TIME_C: { defaultMessage: 'Service End Time:', id: 'SERVICE_END_TIME_C' },
  KYLIN_MDX_COMMIT_C: { defaultMessage: 'Kylin MDX Commit:', id: 'KYLIN_MDX_COMMIT_C' },
  SERVICE_STATEMENT: { defaultMessage: 'Service Statement', id: 'SERVICE_STATEMENT' },
  COPYRIGHT_CONTENT: { defaultMessage: 'Copyright {year} Kyligence Inc. All rights reserved.', id: 'COPYRIGHT_CONTENT' },
  EVALUATION: { defaultMessage: 'Evaluation', id: 'EVALUATION' },
  PROFESSIONAL: { defaultMessage: 'Professional', id: 'PROFESSIONAL' },
  PREMIUM: { defaultMessage: 'Premium', id: 'PREMIUM' },
  EVALUATION_CONTENT: { defaultMessage: `
    <span>You are using Kylin MDX with Evaluation License.</span>
    <br />
    <span>For more product information, expert consulting and services, please </span>
    <a href="mailto:info@Kyligence.io">contact us</a>
    <span>.</span>
    <br />
    <span>We'll get you the help you need from Apache Kylin core team.</span>
  `, id: 'EVALUATION_CONTENT' },
  PURCHASED_CONTENT: { defaultMessage: `
    <span>You have purchased the Kylin MDX products and services.</span>
    <br />
    <span>If you encounter any problems during use, please feel free to </span>
    <a href="mailto:info@Kyligence.io">contact us</a>
    <span>.</span>
    <br />
    <span>We will continue to provide you with quality products and services.</span>
  `, id: 'PURCHASED_CONTENT' },
  // CloneDatasetModal
  DATASET_CLONE: { defaultMessage: 'Dataset Clone', id: 'DATASET_CLONE' },
  DATASET_RENAME: { defaultMessage: 'Dataset Rename', id: 'DATASET_RENAME' },
  NEW_NAME: { defaultMessage: 'New Name', id: 'NEW_NAME' },
  // ExpressionWizardModal
  ENTITY_TEMPLATE: { defaultMessage: '{entity} Template', id: 'ENTITY_TEMPLATE' },
  TEMPLATE: { defaultMessage: 'Template', id: 'TEMPLATE' },
  PLEASE_SELECT_TEMPLATE: { defaultMessage: 'Please select a template from left library.', id: 'PLEASE_SELECT_TEMPLATE' },
  DEFAULT_TEMPLATE: { defaultMessage: 'Default Template', id: 'DEFAULT_TEMPLATE' },
  CUSTOM_TEMPLATE: { defaultMessage: 'Custom Template', id: 'CUSTOM_TEMPLATE' },
  PARAMETERS: { defaultMessage: 'Parameters', id: 'PARAMETERS' },
  USE_TEMPLATE: { defaultMessage: 'Use Templates', id: 'USE_TEMPLATE' },
  CONFIRM_OVERRIDE_EXPRESSION: { defaultMessage: 'The original expression will be replaced, are you sure you want to continue using this template?', id: 'CONFIRM_OVERRIDE_EXPRESSION' },
  // SaveNotExistedModal
  ENTITY_NOT_EXISTED_TIP: { defaultMessage: 'This {entity} has been deleted. You could save a new {entity} based on existing changes, or abandon existing operations.', id: 'ENTITY_NOT_EXISTED_TIP' },
  SAVE_AS: { defaultMessage: 'Save as', id: 'SAVE_AS' },
  GIVE_UP_EDIT: { defaultMessage: 'Give up', id: 'GIVE_UP_EDIT' },
  GIVE_UP_EDIT_TIP: { defaultMessage: 'The {entity} will be deleted.', id: 'GIVE_UP_EDIT_TIP' },
  // FormatSettingModal
  FORMAT_SETTING: { defaultMessage: 'Format Setting', id: 'FORMAT_SETTING' },
  NO_FORMATTING: { defaultMessage: 'No formatting', id: 'NO_FORMATTING' },
  SAMPLE: { defaultMessage: 'Sample', id: 'SAMPLE' },
  DECIMAL_PLACES: { defaultMessage: 'Decimal Places', id: 'DECIMAL_PLACES' },
  USE_1000_SEPARATOR: { defaultMessage: 'Use 1000 Separator', id: 'USE_1000_SEPARATOR' },
  MINUS: { defaultMessage: 'Minus', id: 'MINUS' },
  CURRENCY_FORMAT_TIP: { defaultMessage: 'The currency symbol displayed in the client application may be different from the sample. Please check the regional format setting of the operating system.', id: 'CURRENCY_FORMAT_TIP' },
  CUSTOMIZE_FORMAT_TIP: { defaultMessage: 'To view more custom format types, please refer to the {link}.', id: 'CUSTOMIZE_FORMAT_TIP' },
  FORMAT_DESCRIPTION: { defaultMessage: 'Format Description', id: 'FORMAT_DESCRIPTION' },
  LINK_FORMAT_DOC: { defaultMessage: 'https://docs.kyligence.io/books/mdx/v1.3/en/appendix/formatstring.en.html', id: 'LINK_FORMAT_DOC' },
  NO_FORMAT: { defaultMessage: 'Unformatted', id: 'NO_FORMAT' },
  NUMBER_FORMAT: { defaultMessage: 'Number', id: 'NUMBER_FORMAT' },
  CURRENCY: { defaultMessage: 'Currency', id: 'CURRENCY' },
  PERCENTAGE: { defaultMessage: 'Percentage', id: 'PERCENTAGE' },
  NUMBER_FORMAT_DESC: { defaultMessage: 'Number is used for general display of numbers.', id: 'NUMBER_FORMAT_DESC' },
  CURRENCY_FORMAT_DESC: { defaultMessage: 'Currency format are used for general monetary values.', id: 'CURRENCY_FORMAT_DESC' },
  PERCENTAGE_FORMAT_DESC: { defaultMessage: 'Percentage formats multiplies the value by 100 and displays the result with a percent symbol.', id: 'PERCENTAGE_FORMAT_DESC' },
  CUSTOMIZE_FORMAT_DESC: { defaultMessage: 'Type the number format code,using one the existing codes as a starting point.', id: 'CUSTOMIZE_FORMAT_DESC' },
  CUSTOMIZE_FORMAT_TOO_LONG: { defaultMessage: 'The customize format length cannot be greater than {maxLength}.', id: 'CUSTOMIZE_FORMAT_TOO_LONG' },
  // GlobalAdminMask
  ENTER_ADMIN_MODE: { defaultMessage: 'Welcome to management page.', id: 'ENTER_ADMIN_MODE' },
  LEAVE_ADMIN_MODE: { defaultMessage: 'Going to leave management page.', id: 'LEAVE_ADMIN_MODE' },
  // UPGRADE
  UPGRADE_ALL_DATASETS_START: { defaultMessage: 'System will start to upgrade all datasets.', id: 'UPGRADE_ALL_DATASETS_START' },
  UPGRADING_DATASET: { defaultMessage: 'The system is upgrading the dataset. ({currentCount} / {totalCount})', id: 'UPGRADING_DATASET' },
  UPGRADE_ALL_DATASET_SUCCESS: { defaultMessage: 'The system has completed the upgrade of all data sets.', id: 'UPGRADE_ALL_DATASET_SUCCESS' },
  // Retry Block
  UNKONW_ERROR_TO_RETRY_1: { defaultMessage: 'Can\'t load data.', id: 'UNKONW_ERROR_TO_RETRY_1' },
  UNKONW_ERROR_TO_RETRY_2: { defaultMessage: 'Please click to try again.', id: 'UNKONW_ERROR_TO_RETRY_2' },
  // Error Messages
  ERROR_KE_CONNECT: { defaultMessage: 'Can\'t connect to Kylin. Please contact your administrator to check that Kylin is working properly.', id: 'ERROR_KE_CONNECT' },
  ERROR_MDX_CONNECT: { defaultMessage: 'Unable to connect to Kylin MDX. Please check if your internet connection is normal.', id: 'ERROR_MDX_CONNECT' },
  ERROR_UNKNOW: { defaultMessage: 'Unknow error.', id: 'ERROR_UNKNOW' },
  ERROR_400: { defaultMessage: 'Incorrect operation. Please click the details button for more details.', id: 'ERROR_400' },
  ERROR_500: { defaultMessage: 'The operation is abnormal. Please click the details button for more details. You can also contact Kylin Community for more help.', id: 'ERROR_500' },
  'MDX-04010005': { defaultMessage: '[MDX-04010005] Invalid username or password.', id: 'MDX-04010005' },
  'MDX-01020001': { defaultMessage: '[MDX-01020001] The system lacks user information for syncing Kylin tasks. \r\nPlease log in to Kylin MDX with a Kylin system administrator account to configure connection information.', id: 'MDX-01020001' },
  'MDX-04010004': { defaultMessage: '[MDX-04010004] Access denied. Only Kylin system administrators or project administrators can access the Kylin MDX UI interface.', id: 'MDX-04010004' },
  'MDX-04010002': { defaultMessage: '[MDX-04010002] Invalid username or password.', id: 'MDX-04010002' },
  'MDX-04020002': { defaultMessage: '[MDX-04020002] User is disabled in Kylin.', id: 'MDX-04020002' },
  'MDX-04010002_SYNC': { defaultMessage: '[MDX-04010002] Invalid username or password. You can click Edit User Information to modify the username and password for connecting to Kylin.', id: 'MDX-04010002_SYNC' },
  'MDX-01050001': { defaultMessage: '[MDX-01050001] Can\'t connect to Kylin. Please contact your administrator to check that Kylin is working properly.', id: 'MDX-01050001' },
  'MDX-04020001': { defaultMessage: '[MDX-04020001] The user [{username}] is not a system administrator.', id: 'MDX-04020001' },
  'MDX-04020001_SYNC': { defaultMessage: '[MDX-04020001] The user [{username}] is not a system administrator. You can click Edit User Information to modify the username and password for connecting to Kylin.', id: 'MDX-04020001_SYNC' },
  'MDX-04020001_ACCESS': { defaultMessage: '[MDX-04020001] Access denied! There is no right!', id: 'MDX-04020001_ACCESS' },
  'MDX-01060002': { defaultMessage: '[MDX-01060002] The dataset role named [{datasetName}] already exists.', id: 'MDX-01060002' },
  'MDX-01060009': { defaultMessage: '[MDX-01060009] User is assigned with dataset role [{roleName}] which cannot be deleted.', id: 'MDX-01060009' },
  'MDX-01040003': { defaultMessage: '[MDX-01040003] The operation request is incorrect. It is recommended to check the configuration of Nginx.', id: 'MDX-01040003' },
  'MDX-01010002': { defaultMessage: '[MDX-01010002] Kylin License has expired.', id: 'MDX-01010002' },
  'MDX-03050001': { defaultMessage: '[MDX-03050001] The total file size cannot exceed configured limit.', id: 'MDX-03050001' },
  'MDX-02020026': { defaultMessage: '[MDX-02020026] Dataset package parse error.', id: 'MDX-02020026' },
});

export const stringsMap = {
  1002: strings['MDX-04010002'],
  1003: strings['MDX-04020002'],
  1004: strings['MDX-01010002'],
  1005: strings.ERROR_UNKNOW,
  1009: strings['MDX-01020001'],
  'MDX-01060002': totalMessage => {
    const message = strings['MDX-01060002'];
    const datasetName = totalMessage
      .replace('[MDX-01060002] The dataset role named [', '')
      .replace('] already exists.', '');
    const data = { datasetName };

    return { message, data };
  },
  'MDX-01060009': totalMessage => {
    const message = strings['MDX-01060009'];
    const roleName = totalMessage
      .replace('[MDX-01060009] User is assigned with dataset role [', '')
      .replace('] which cannot be deleted.', '');
    const data = { roleName };

    return { message, data };
  },
  'MDX-04020001': totalMessage => {
    const username = totalMessage
      .split('\n')[0]
      .replace('[MDX-04020001] The user [', '')
      .replace('[MDX-04020001] [NOT_KYLIN_ADMIN]The user [', '')
      .replace('] is not a system administrator.', '')
      .replace('[MDX-04020001] Access denied! There is no right!', '');

    const message = username ? strings['MDX-04020001'] : strings['MDX-04020001_ACCESS'];
    const data = { username };

    return { message, data };
  },
  'MDX-04020001_SYNC': totalMessage => {
    const message = strings['MDX-04020001_SYNC'];
    const username = totalMessage
      .replace('[MDX-04020001] The user [', '')
      .replace('] is not a system administrator.', '');
    const data = { username };

    return { message, data };
  },
};

export default strings;
