-- 测试 CrossJoin，包含一个行列过滤器和额外筛选器
SELECT
  {[Measures].[MAX_PRICE],[Measures].[MIN_PRICE],[Measures].[SUM_PRICE]} DIMENSION PROPERTIES PARENT_UNIQUE_NAME ON COLUMNS ,
  NON EMPTY CrossJoin(
    Hierarchize(AddCalculatedMembers({DrilldownLevel({[KYLIN_ACCOUNT].[ACCOUNT_COUNTRY].[All]})})),
    Hierarchize(AddCalculatedMembers({DrilldownLevel({[KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].[All]})}))
  ) DIMENSION PROPERTIES PARENT_UNIQUE_NAME ON ROWS
FROM (
  SELECT
    (
      {[KYLIN_ACCOUNT].[ACCOUNT_COUNTRY].&[JP], [KYLIN_ACCOUNT].[ACCOUNT_COUNTRY].&[CN]},
      {[KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[2], [KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[1], [KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[0]}
    ) ON COLUMNS
  FROM (
    SELECT
      ({[KYLIN_COUNTRY].[COUNTRY].&[AG],[KYLIN_COUNTRY].[COUNTRY].&[AI],[KYLIN_COUNTRY].[COUNTRY].&[AL]}) ON COLUMNS
    FROM [learn_kylin]
  )
)
CELL PROPERTIES VALUE, FORMAT_STRING, LANGUAGE, BACK_COLOR, FORE_COLOR, FONT_FLAGS
-- MDX --
WITH
  SET [XL_Row_Dim_0] AS 'VisualTotals(Distinct(Hierarchize({Ascendants([KYLIN_ACCOUNT].[ACCOUNT_COUNTRY].&[JP]), Descendants([KYLIN_ACCOUNT].[ACCOUNT_COUNTRY].&[JP]), Ascendants([KYLIN_ACCOUNT].[ACCOUNT_COUNTRY].&[CN]), Descendants([KYLIN_ACCOUNT].[ACCOUNT_COUNTRY].&[CN])})))'
  SET [XL_Row_Dim_1] AS 'VisualTotals(Distinct(Hierarchize({Ascendants([KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[2]), Descendants([KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[2]), Ascendants([KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[1]), Descendants([KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[1]), Ascendants([KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[0]), Descendants([KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].&[0])})))'
  MEMBER [KYLIN_COUNTRY].[COUNTRY].[Slicer_0] AS 'Aggregate({[KYLIN_COUNTRY].[COUNTRY].&[AG], [KYLIN_COUNTRY].[COUNTRY].&[AI], [KYLIN_COUNTRY].[COUNTRY].&[AL]})'
SELECT
  {[Measures].[MAX_PRICE], [Measures].[MIN_PRICE], [Measures].[SUM_PRICE]} DIMENSION PROPERTIES PARENT_UNIQUE_NAME ON COLUMNS,
  NON EMPTY CrossJoin(
    Hierarchize(Intersect(AddCalculatedMembers({DrilldownLevel({[KYLIN_ACCOUNT].[ACCOUNT_COUNTRY].[All]})}), [XL_Row_Dim_0])),
    Hierarchize(Intersect(AddCalculatedMembers({DrilldownLevel({[KYLIN_ACCOUNT].[ACCOUNT_BUYER_LEVEL].[All]})}), [XL_Row_Dim_1]))
  ) DIMENSION PROPERTIES PARENT_UNIQUE_NAME ON ROWS
FROM [learn_kylin]
WHERE ([KYLIN_COUNTRY].[COUNTRY].[Slicer_0])
CELL PROPERTIES [VALUE],[FORMAT_STRING],[LANGUAGE],[BACK_COLOR],[FORE_COLOR],[FONT_FLAGS]